name: Release

on:
  push:
    tags:
      - "Ver.[0-9]+.[0-9]+.[0-9]+"
      - "Ver.[0-9]+.[0-9]+.[0-9]+pre"
  workflow_dispatch:


permissions:
    contents: write
    actions: write
    
jobs:
  trigger_build_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const response = await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              workflow_file: 'build.yml',
              ref: 'main'
            });
            console.log('triggered build workflow');

  wait_for_build_workflow:
    needs: trigger_build_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build workflow to complete
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { owner, repo } = github.context.repo;
            let status = 'in_progress';
            while (status === 'in_progress') { 
              await new Promise(resolve => setTimeout(resolve, 5000));
              const runs = await github.actions.listRepoWorkflowRuns({
                owner,
                repo,
                workflow_id: 'build.yml',
                status: 'in_progress',
                per_page: 1,
              });
              if (runs.data.total_count === 0) {
                status = 'completed';
                console.log('build workflow completed');
              }
            }