name: Triage and Dispatch

on: 
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - master  # Trigger on pull request to master

jobs:
  dispatch_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Dispatch build workflow and get the run ID
        id: dispatch_build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.AUTH_GITHUB_API }}
          ref: ${{ github.ref }}

      - name: Use the output run ID and URL
        run: |
          echo "Run ID: ${{ steps.dispatch_build.outputs.run_id }}"
          echo "Run URL: ${{ steps.dispatch_build.outputs.run_url }}"
          echo "::set-output name=run_url::${{ steps.dispatch_build.outputs.run_url }}"

      - name: Create a comment with the build URL
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.AUTH_GITHUB_API }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Build workflow has been triggered. [View build](${{ steps.dispatch_build.outputs.run_url }})"